### ISSUE TITLE
Stop my staxrip

### ISSUE THREAD

**Issue by hintlou** [jpsdr/plugins_JPSDR#3]
I make dvdrip in staxrip 2.0.8 x64.
Today I updated the plugins_JPSDR.dll from ver. 3.2.0 to 3.2.1.
But the x264.exe of the staxrip has no response when I start a job.
I have to use the 3.2.0 version plugins_JPSDR.dll which can work normally in my staxrip.

**Comment by jpsdr** [comment]
What's your avisynth script ?
What build version (clang, AVX, etc...) ?
If you open your avisynth script in VirtualDub, is it working ?
I don't use staxrip (so don't care too much), and i'm not sure if i'll be able to figure out (even more if it's working fine in VDub...).
Anyway, for now, i'm waiting for the input i've asked, will see...

**Comment by hintlou** [comment]
I tried clang w7+avx+avx2,w7+avx+avx2. All of them failed.
my avs:
MPEG2Source("C:\DVD\VIDEO_TS\李克勤 再见穿梭机_temp\李克勤 再见穿梭机.d2v")
QTGMC(preset="Very Slow", InputType=0,sourceMatch=3, sharpness=0.2, tr2=2, ediThreads=8).SelectEven()

It's a simple avs script that I use often.It won't get error usually.

I put my  script to simple x264/265 launcher and got a log:
[李克勤 再见穿梭机0.hevc.log](https://github.com/jpsdr/plugins_JPSDR/files/4578801/0.hevc.log)
Hope it can give u help.

**Comment by jpsdr** [comment]
Did your script work properly when opened with VDub ?

In the meantime, someone reported issue with QTGMC, it's probably related.
Can you try the following scripts and report results (error with x265 launcher or not) :

MPEG2Soure(...)
nnedi3(threads=0)

The same with threads=1.

MPEG2Soure(...)
Spline36ResizeMT(1280,720,threads=0)

The same with threads=1

This will help me (i hope...) to identify where issue comes from.

**Comment by hintlou** [comment]
all scripts can be started working with VD.I don't know what I can report to you.

**Comment by jpsdr** [comment]
You can report just what i've asked, if the 4 small scripts produce error or not with the x264 launcher.

**Comment by hintlou** [comment]
Your scripts work properly when opened with VDub.
there're logs of your scripts working on  x264 launcher.

[Spline36ResizeMT(1280,720,threads=1).log](https://github.com/jpsdr/plugins_JPSDR/files/4580639/Spline36ResizeMT.1280.720.threads.1.log)
 
[nnedi3(threads=0).log](https://github.com/jpsdr/plugins_JPSDR/files/4580640/nnedi3.threads.0.log)

[nnedi3(threads=1).log](https://github.com/jpsdr/plugins_JPSDR/files/4580635/nnedi3.threads.1.log)
[Spline36ResizeMT(1280,720,threads=0).log](https://github.com/jpsdr/plugins_JPSDR/files/4580636/Spline36ResizeMT.1280.720.threads.0.log)

**Comment by jpsdr** [comment]
I know they worked with VDub, that's not what i wanted to know.
But it seems that they're all working and not creating an issue, good...
I've struggled getting the simple following script (3.364) working:
ColorBars(width=640, height=480, pixel_type="yv12")
QTGMC().SelectEven()

Finaly, i made this script working on VDub. Then, i checked your post, and tried the following;
ColorBars(width=640, height=480, pixel_type="yv12")
QTGMC(preset="Very Slow", InputType=0,sourceMatch=3, sharpness=0.2, tr2=2, ediThreads=8).SelectEven()

I didn't work because i didn't have FFT3DFilter... After getting it, i'll struggle to get the libff3w, finaly i found a very (v3.3.7) recent build on doom9.
Then, when i opened the script in VDub... Crash error within avisynth. So, it seems that in QTGMC script, when FFT3Dfilter is involved, it's not good.
Last test i want you to make, in your script, replace:
QTGMC(preset="Very Slow", InputType=0,sourceMatch=3, sharpness=0.2, tr2=2, ediThreads=8).SelectEven()
with:
QTGMC().SelectEven()
And eventualy add _trim(0,199)_ at the end, no need to encode 7000 frames, i just want to know if the launcher is stuck or not.

**Comment by hintlou** [comment]
[QTGMC().SelectEven()trim(0,199).log](https://github.com/jpsdr/plugins_JPSDR/files/4580884/QTGMC.SelectEven.trim.0.199.log)

**Comment by jpsdr** [comment]
Ok, finaly it was an issue within nnedi3, tell me if it's working properly with the new release.

**Comment by hintlou** [comment]
Thanks! I updated nnedi3.dll and plugins_JPSDR.dll.
It worked well now!

**Comment by jpsdr** [comment]
...?? If you use plugins_JPSDR.dll, you don't need nnedi3.dll, as it's allready included. You may have a lot of unecessary threads created and a waste of resources.
Anyway, it's fixed, so i close.
